/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Control.ManejadorFechas;
import com.sun.scenario.effect.InvertMask;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Gaby
 */
public class Administracion extends javax.swing.JFrame implements Runnable{
    int posx, posy;
    String hora, minutos, segundos, ampm;
    Calendar calendario;
    Thread h1;
    
    public Administracion() {
        setUndecorated(true);
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        lbl_fecha.setText(new ManejadorFechas().fechaCadena());
        h1 = new Thread(this);
        h1.start();
    }
    
    public void calcular() {
        calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();        
        
        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";

        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }
    
    public String obtener_hora() {
        String hora = "";
        calcular();
        hora = (this.hora + ":" + minutos + ":" + segundos + " " + ampm);
        return hora;
    }
    
    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            calcular();
            lbl_hora.setText(hora + ":" + minutos + ":" + segundos + " " + ampm);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_hora = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_asistencia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_clientes = new javax.swing.JButton();
        btn_flujocaja = new javax.swing.JButton();
        btn_inventario = new javax.swing.JButton();
        btn_ventas = new javax.swing.JButton();
        btn_compras = new javax.swing.JButton();
        btn_usuario = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_proveedores = new javax.swing.JButton();
        btn_gastos = new javax.swing.JButton();
        btn_stock = new javax.swing.JButton();
        btn_configuracion = new javax.swing.JButton();
        btn_ayuda = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_foco = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_hora.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hora.setText("11:00 PM");
        jPanel1.add(lbl_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        lbl_fecha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha.setText("MARTES 09 DE FEBRERO DEL 2016");
        jPanel1.add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 200, -1));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("RENALI DISTRIBUIDORES");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 100));

        btn_asistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_asistencia.png"))); // NOI18N
        btn_asistencia.setBorder(null);
        btn_asistencia.setBorderPainted(false);
        btn_asistencia.setContentAreaFilled(false);
        btn_asistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_asistencia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_asistencia_press.png"))); // NOI18N
        btn_asistencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_asistencia_big.png"))); // NOI18N
        btn_asistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asistenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 130, 110));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1150, 20));

        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_clientes.png"))); // NOI18N
        btn_clientes.setBorder(null);
        btn_clientes.setBorderPainted(false);
        btn_clientes.setContentAreaFilled(false);
        btn_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clientes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_clientes_press.png"))); // NOI18N
        btn_clientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_clientes_big.png"))); // NOI18N
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 130, 110));

        btn_flujocaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_flujo_caja.png"))); // NOI18N
        btn_flujocaja.setBorder(null);
        btn_flujocaja.setBorderPainted(false);
        btn_flujocaja.setContentAreaFilled(false);
        btn_flujocaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_flujocaja.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_flujo_caja_press.png"))); // NOI18N
        btn_flujocaja.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_flujo_caja_big.png"))); // NOI18N
        btn_flujocaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_flujocajaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_flujocaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 130, 110));

        btn_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_inventario.png"))); // NOI18N
        btn_inventario.setBorder(null);
        btn_inventario.setBorderPainted(false);
        btn_inventario.setContentAreaFilled(false);
        btn_inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_inventario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_inventario_press.png"))); // NOI18N
        btn_inventario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_inventario_big.png"))); // NOI18N
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 130, 110));

        btn_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_venta.png"))); // NOI18N
        btn_ventas.setBorder(null);
        btn_ventas.setBorderPainted(false);
        btn_ventas.setContentAreaFilled(false);
        btn_ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ventas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_venta_press.png"))); // NOI18N
        btn_ventas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_venta_big.png"))); // NOI18N
        btn_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ventasMouseEntered(evt);
            }
        });
        btn_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 130, 110));

        btn_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_compra.png"))); // NOI18N
        btn_compras.setBorder(null);
        btn_compras.setBorderPainted(false);
        btn_compras.setContentAreaFilled(false);
        btn_compras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_compras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_compra_press.png"))); // NOI18N
        btn_compras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_compra_big.png"))); // NOI18N
        btn_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 130, 110));

        btn_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_usuario.png"))); // NOI18N
        btn_usuario.setBorder(null);
        btn_usuario.setBorderPainted(false);
        btn_usuario.setContentAreaFilled(false);
        btn_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_usuario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_usuario_press.png"))); // NOI18N
        btn_usuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_usuario_big.png"))); // NOI18N
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 130, 110));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_salir.png"))); // NOI18N
        btn_salir.setBorder(null);
        btn_salir.setBorderPainted(false);
        btn_salir.setContentAreaFilled(false);
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_salir_press.png"))); // NOI18N
        btn_salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_salir_big.png"))); // NOI18N
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 410, 130, 110));

        btn_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_proveedores.png"))); // NOI18N
        btn_proveedores.setBorder(null);
        btn_proveedores.setBorderPainted(false);
        btn_proveedores.setContentAreaFilled(false);
        btn_proveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_proveedores.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_proveedores_press.png"))); // NOI18N
        btn_proveedores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_proveedore_big.png"))); // NOI18N
        btn_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 130, 110));

        btn_gastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_gastos.png"))); // NOI18N
        btn_gastos.setBorder(null);
        btn_gastos.setBorderPainted(false);
        btn_gastos.setContentAreaFilled(false);
        btn_gastos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_gastos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_gastos_press.png"))); // NOI18N
        btn_gastos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_gastos_big.png"))); // NOI18N
        btn_gastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gastosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 130, 110));

        btn_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_stock.png"))); // NOI18N
        btn_stock.setBorder(null);
        btn_stock.setBorderPainted(false);
        btn_stock.setContentAreaFilled(false);
        btn_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_stock.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_stock_press.png"))); // NOI18N
        btn_stock.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_stock_big.png"))); // NOI18N
        btn_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stockActionPerformed(evt);
            }
        });
        getContentPane().add(btn_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 130, 110));

        btn_configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_configuracion.png"))); // NOI18N
        btn_configuracion.setBorder(null);
        btn_configuracion.setBorderPainted(false);
        btn_configuracion.setContentAreaFilled(false);
        btn_configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_configuracion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_configuracion_press.png"))); // NOI18N
        btn_configuracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_configuracion_big.png"))); // NOI18N
        btn_configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 130, 110));

        btn_ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_ayuda.png"))); // NOI18N
        btn_ayuda.setBorder(null);
        btn_ayuda.setBorderPainted(false);
        btn_ayuda.setContentAreaFilled(false);
        btn_ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ayuda.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_ayuda_press.png"))); // NOI18N
        btn_ayuda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/btn_ayuda_big.png"))); // NOI18N
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 130, 110));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Distribucion y Venta");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Juegos didácticos");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Papelería en general");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Útiles escolares");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Artículos de oficina");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Insumos");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Textos");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Productos de importación");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 10, 180));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Of. Principal");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jr. Mantaro 463 Piso 3 Of. 301 - Hyo");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tienda");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Jr. Huamanmarca N° 136 - Hyo.");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Jr. Mantaro N° 428 - Hyo");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Teléfonos");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("064 627272 - 064 213690");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1170, 180));

        lbl_foco.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lbl_foco.setForeground(new java.awt.Color(255, 255, 255));
        lbl_foco.setText("______________");
        getContentPane().add(lbl_foco, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/elegant-abstract-blue-powerpoint-ppt-backgrounds-powerpoint.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1170, 440));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_asistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asistenciaActionPerformed
        new Asistencias().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_asistenciaActionPerformed

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        new Clientes().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_flujocajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_flujocajaActionPerformed
        new Flujo_caja().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_flujocajaActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        new Inventario().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void btn_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventasActionPerformed
        new Ventas().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_ventasActionPerformed

    private void btn_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprasActionPerformed
        new Compras().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_comprasActionPerformed

    private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarioActionPerformed
        new Usuarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_usuarioActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedoresActionPerformed
        new Proveedores().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_proveedoresActionPerformed

    private void btn_gastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gastosActionPerformed
        new Gastos().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_gastosActionPerformed

    private void btn_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stockActionPerformed
        new Stock().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_stockActionPerformed

    private void btn_configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionActionPerformed
        new Configuracion().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_configuracionActionPerformed

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        new Ayuda().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x-posx, point.y-posy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btn_ventasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ventasMouseEntered
       
        
    }//GEN-LAST:event_btn_ventasMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_asistencia;
    private javax.swing.JButton btn_ayuda;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_compras;
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JButton btn_flujocaja;
    private javax.swing.JButton btn_gastos;
    private javax.swing.JButton btn_inventario;
    private javax.swing.JButton btn_proveedores;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_stock;
    private javax.swing.JButton btn_usuario;
    private javax.swing.JButton btn_ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_foco;
    private javax.swing.JLabel lbl_hora;
    // End of variables declaration//GEN-END:variables
}
