/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Control.Conexion;
import Control.ManejadorFechas;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaby
 */
public final class Flujo_caja extends javax.swing.JFrame {
    int posx = 0, posy = 0;
    Connection con = new Conexion().conectar();
    DefaultTableModel model_diario;
    
    public Flujo_caja() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        cargarTitulos();
    }
    
    
    public void cargarTitulos(){
        String titulos[] = {"VENTA","FECHA","HORA","TRABAJADOR"};
        model_diario = new DefaultTableModel(null, titulos);
        tbl_diario.setModel(model_diario);
        String fecha = new ManejadorFechas().getFechaActualMySQL();
        cargarTabla(fecha);
        //flujoDia(fecha);
    }
    
    public void cargarTabla(String fecha){
        limpiarTabla();
        String datos[] = new String[4];
        String sql = "SELECT `id`, `fecha`, `hora_venta`, `id_usu` FROM `venta` WHERE `fecha`= '"+fecha+"'";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0]=rs.getString("id");
                datos[1]=rs.getString("fecha");
                datos[2]=rs.getString("hora_venta");
                datos[3]=rs.getString("id_usu");
                model_diario.addRow(datos);
            }
            tbl_diario.setModel(model_diario);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public double calcularIngresos(String fecha){
        double ing=0.0;
        String sql = "SELECT SUM(venta_detalle.subtotal) FROM venta INNER JOIN venta_detalle on venta.id = venta_detalle.id where venta.fecha = '"+fecha+"' ";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                ing = ing + (rs.getDouble("SUM(venta_detalle.subtotal)"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return ing;
    }
    
    public int flujoDia(String fecActual){
        int opc = 0;
        double ingresos = 0.0;
        String datos[] = new String[4];
        String sql = "SELECT `id`, `fecha`, `hora_venta`, `id_usu`, `id_cli` FROM `venta`";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                if (rs.getString("fecha").equals(fecActual)) {
                    opc = opc+1;
                    int filas = tbl_diario.getRowCount();
                    txt_ventas_diario.setText(""+filas);
                } else {
                }
                txt_ventas_diario.setText(""+opc);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        return opc;
    }
    
    public double getGastos(String fecha){
        double opc=0.0;
        String sql = "SELECT SUM(`monto`) FROM `tgastos` WHERE `fecha_gasto` = '"+fecha+"'";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {                
                opc = rs.getDouble("SUM(`monto`)");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return opc;
    }
    
    public void getBalance(){
        double ingresos = Double.parseDouble(txt_ingresos_diario.getText());
        double gastos = Double.parseDouble(txt_gastos_diario.getText());
        double balance = ingresos - gastos;
        txt_balance_diario.setText(""+balance);
    }
    
    public void limpiarTabla() {
        for (int i = 0; i < tbl_diario.getRowCount(); i++) {
            model_diario.removeRow(i);
            i -= 1;
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_salir = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_diario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_ventas_diario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ingresos_diario = new javax.swing.JTextField();
        txt_gastos_diario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_balance_diario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_revisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jdc_fecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("FLUJO DE CAJA");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("11:00 PM");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        lbl_fecha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha.setText("Viernes, 24 de Diciembre del 2015");
        jPanel1.add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 230, -1));

        lbl_salir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_salir.setForeground(new java.awt.Color(255, 255, 255));
        lbl_salir.setText("SALIR");
        lbl_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_salirMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        jPanel2.setBackground(new java.awt.Color(102, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_diario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_diario);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 320));

        jLabel1.setText("FECHA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel2.add(txt_ventas_diario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 90, -1));

        jLabel4.setText("INGRESOS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel2.add(txt_ingresos_diario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 90, -1));
        jPanel2.add(txt_gastos_diario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 90, -1));

        jLabel5.setText("GASTOS");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanel2.add(txt_balance_diario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 90, -1));

        jLabel6.setText("BALANCE");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        btn_revisar.setText("REVISAR");
        btn_revisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_revisarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_revisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 90, -1));

        jLabel2.setText("TOTAL VENTAS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jdc_fecha.setDateFormatString("yyyy/MM/dd");
        jdc_fecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel2.add(jdc_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 140, -1));

        jLabel3.setText("VENTAS EL DÍA DE HOY");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jTabbedPane1.addTab("DIARIO", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseClicked
        dispose();
        new Administracion().setVisible(true);        
    }//GEN-LAST:event_lbl_salirMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x-posx, point.y-posy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void btn_revisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_revisarActionPerformed
        String fecha = new ManejadorFechas().getFechaActualMySQL();
        //lbl_getFecha.setText(fecha);
        try {
            //String formato = jdc_fecha.getDateFormatString();
            Date date = jdc_fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String ff = String.valueOf(sdf.format(date));
            cargarTabla(ff);
            int filas = tbl_diario.getRowCount();
            txt_ventas_diario.setText(""+filas);
            txt_ingresos_diario.setText(""+calcularIngresos(ff));
            txt_gastos_diario.setText(""+getGastos(ff));
            getBalance();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fecha no valida", "Error..!!", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btn_revisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flujo_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flujo_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flujo_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flujo_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flujo_caja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_revisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdc_fecha;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_salir;
    private javax.swing.JTable tbl_diario;
    private javax.swing.JTextField txt_balance_diario;
    private javax.swing.JTextField txt_gastos_diario;
    private javax.swing.JTextField txt_ingresos_diario;
    private javax.swing.JTextField txt_ventas_diario;
    // End of variables declaration//GEN-END:variables
}
