/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;

/**
 *
 * @author Adolfo
 */
public class Presentacion extends javax.swing.JFrame {
    private  int auxiliar = 0;
    private  boolean realizado = false;
    hilo h = new hilo();
    
    public Presentacion() {
        setUndecorated(true);
        initComponents();
        Presentacion.this.getRootPane().setOpaque(false);//para que no se vea nada
        Presentacion.this.getContentPane().setBackground(new Color (0,0,0,0));//establece color rgb y por ultimo transparencia
        Presentacion.this.setBackground(new Color (0,0,0,0));//
        this.setResizable(false);//hace que el programa no se pueda redimensionar     
        setLocation(320, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_texto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_texto.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbl_progress.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbl_progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 800, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (realizado==false) {
            realizado = true;
            lbl_progress.setMaximum(49);
            lbl_progress.setMinimum(0);
            lbl_progress.setStringPainted(true);
            lbl_progress.setBackground(Color.red);
            h.start();
        }
    }//GEN-LAST:event_formWindowActivated
                
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar lbl_progress;
    private javax.swing.JLabel lbl_texto;
    // End of variables declaration//GEN-END:variables

private class hilo extends Thread {

        @Override
        public void run() {
            try {
                while (true) {
                    auxiliar++;
                    lbl_progress.setValue(auxiliar);
                    repaint();
                    switch (auxiliar) {
                        case 0:
                            lbl_texto.setText("Cargando programa....");
                            break;
                        case 10:
                            lbl_texto.setText("Leyendo preferencias....");
                            break;
                        case 20:
                            lbl_texto.setText("Cargando módulos....");
                            break;
                        case 30:
                            lbl_texto.setText("Verificando sesiones....");
                            break;
                        case 40:
                            lbl_texto.setText("Carga finalizada....");
                            break;
                        case 50:
                            Login p = new Login() ;
                            p.setVisible(true);
                            p.setLocationRelativeTo(null);
                            Presentacion.this.dispose();
                            break;
                    }
                    Thread.sleep(40);
                }

            } catch (Exception e) {
            }

        }
    }
}
