/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Control.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaby
 */
public final class RevisionCompras extends javax.swing.JFrame {
    DefaultTableModel model;
    Connection con = new Conexion().conectar();
    public RevisionCompras() {
        initComponents();
        cabecera();
    }
    
    
    public void cabecera(){
        String cabecera[]= {"COMPRA","NOMBRE","CANTIDAD","P.UNITARIO","SUBTOTAL"};
        model = new DefaultTableModel(null, cabecera);
        tbl_compras.setModel(model);
    }

    public void cargarTabla(){
        limpiarTabla();
        int idCompra = Integer.parseInt(txt_num_compra.getText());
        String datos[] = new String[5];
        String sql = "SELECT `id_compra`, `descripcion`, `cantidad`, producto.precio, `subtotal` FROM `tdetallecompra` INNER JOIN producto on tdetallecompra.id_compra = producto.id WHERE `id_compra` = " + idCompra + " ";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString("id_compra");
                datos[1] = rs.getString("descripcion");
                datos[2] = rs.getString("cantidad");
                datos[3] = rs.getString("precio");
                datos[4] = rs.getString("subtotal");
                model.addRow(datos);
                tbl_compras.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            txt_buscar.requestFocus();
        }
    }
    
    public void cargarCompra(){
        limpiarCampos();
        int idCompra = Integer.parseInt(txt_num_compra.getText());
        int tipo = 0;
        String sql = "SELECT `id_compra`, `num_doc`, `forma_pago`, `fecha_compra`, `hora_compra`, `idtipo`, `proveedor` FROM `tcompras` WHERE id_compra=" + idCompra + " ";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                tipo = rs.getInt("idtipo");
                switch (tipo) {
                    case 1:
                        txt_tipo_doc.setText("Boleta");
                        break;
                    case 2:
                        txt_tipo_doc.setText("Factura");
                        break;
                }
            }
            txt_num_doc.setText(rs.getString("num_doc"));
            txt_forma_pago.setText(rs.getString("forma_pago"));
            txt_fecha.setText(rs.getString("fecha_compra"));
            txt_hora.setText(rs.getString("hora_compra"));
            txt_proveedor.setText(rs.getString("proveedor"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public double calcularIgv(){
        double igv = 0.0, total= 0.0;
        int filas = tbl_compras.getRowCount();
        try {
            for (int i = 0; i < filas; i++) {
                total = total + Double.parseDouble(tbl_compras.getValueAt(i, 3).toString());
            }
            igv = 0.18*total;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return igv;
    }
    
    public double calcularTotal(double igv){
        double total= 0.0;
        int filas = tbl_compras.getRowCount();
        try {
            for (int i = 0; i < filas; i++) {
                total = total + Double.parseDouble(tbl_compras.getValueAt(i, 4).toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return total+igv;
    }
    
    
    
    public void limpiarCampos(){
        txt_tipo_doc.setText("");
        txt_num_doc.setText("");
        txt_forma_pago.setText("");
        txt_fecha.setText("");
        txt_hora.setText("");
        txt_proveedor.setText("");
    }
    
    
    public void limpiarTabla() {
        for (int i = 0; i < tbl_compras.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_num_compra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_compras = new javax.swing.JTable();
        txt_buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_num_doc = new javax.swing.JTextField();
        txt_tipo_doc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_forma_pago = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_hora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_proveedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_igv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NUMERO DE COMPRA:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        getContentPane().add(txt_num_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 80, -1));

        tbl_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_compras);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 560, 180));

        txt_buscar.setText("BUSCAR");
        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel2.setText("NUMERO DOCUMENTO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel3.setText("DOCUMENTO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(txt_num_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 80, -1));
        getContentPane().add(txt_tipo_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 80, -1));

        jLabel4.setText("FORMA DE PAGO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        getContentPane().add(txt_forma_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 80, -1));

        jLabel5.setText("FECHA:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 80, -1));

        jLabel6.setText("HORA:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));
        getContentPane().add(txt_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 80, -1));

        jLabel7.setText("PROVEEDOR:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        getContentPane().add(txt_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 360, -1));

        jLabel8.setText("TOTAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 80, -1));

        jLabel9.setText("IGV");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));
        getContentPane().add(txt_igv, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 80, -1));

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("REVISAR COMPRAS");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 250, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        cargarTabla();
        cargarCompra();
        double igv = calcularIgv();
        double total = calcularTotal(igv);
        txt_igv.setText(""+igv);
        txt_total.setText(""+total);
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Administracion().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevisionCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevisionCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevisionCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevisionCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevisionCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_compras;
    private javax.swing.JButton txt_buscar;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_forma_pago;
    private javax.swing.JTextField txt_hora;
    private javax.swing.JTextField txt_igv;
    private javax.swing.JTextField txt_num_compra;
    private javax.swing.JTextField txt_num_doc;
    private javax.swing.JTextField txt_proveedor;
    private javax.swing.JTextField txt_tipo_doc;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
